### ISSUE TITLE
error espcap.py 

### ISSUE THREAD

**Issue by testpazio** [vichargrave/espcap#1]
Hello, 
Thanks for your work.
I need your help cause i got an issue when i run this command:
./espcap.py --file=/test_pcaps/test_http.pcap --node=localhost:9200
I have this error 
![image](https://user-images.githubusercontent.com/50212800/57094944-13170900-6ce8-11e9-8ccf-da9ed1c0ec27.png)
![image](https://user-images.githubusercontent.com/50212800/57095286-e0b9db80-6ce8-11e9-961d-63bfa79bdc63.png)

**Comment by vichargrave** [comment]
I've never seen an error like that.  I notice you are using Python 3.6, I wonder if that is an issue.  Also I'd check your Elasticsearch version.  Finally are you sending this data to a remote Elasticsearch system or is it running locally?  I'll do some additional testing to see if I can reproduce this error.

**Comment by vichargrave** [comment]
Ok I tried with a remote Elasticsearch and got a similar problem.  I'm trying to use an Elasticsearch 7.0.0 Python client with an Elasticsearch 6.7.1 server.  I'm wondering if that is one of the problems.

**Comment by vichargrave** [comment]
OK when I use an Elasticsearch 7.x Python client with an Elasticsearch 7.x server then the packets are sent over.  So that is most likely your problem.  I'll make an update that to the requirements that takes this difference into account.  I'm thinking the best way to handle this is to use virtual environments and have  a separate requirements.txt file for Elasticsearch 6.x and 7.x.

**Comment by vichargrave** [comment]
Ok I made the updates.  I'll do more testing.  In the meantime, give this a try and see how it goes.

**Comment by testpazio** [comment]
> 
> 
> I've never seen an error like that. I notice you are using Python 3.6, I wonder if that is an issue. Also I'd check your Elasticsearch version. Finally are you sending this data to a remote Elasticsearch system or is it running locally? I'll do some additional testing to see if I can reproduce this error.

I'm using Elasticsearch server 6.7.1, running localy. i'll test your solution. So thank you very much for your help and your work.

**Comment by testpazio** [comment]
Ok When i execute pip - r requirement-6.txt i have an error. "no matching distribution with 6.7.1"
![image](https://user-images.githubusercontent.com/50212800/58417247-9236fd00-805a-11e9-9165-77fc17b1b267.png)

**Comment by testpazio** [comment]
OK i'm testing with elasticsearch 7.0.1 "pip -r requirement-7.txt"has been successfully executed.
