### ISSUE TITLE
Count variable not defined

### ISSUE THREAD

**Issue by srpatatas** [vichargrave/espcap#2]
Hi Vic, I was trying to test the example on the readme file and I'm getting this error:

./espcap.py --file=../test_pcaps/test_http.pcap --node=x.x.x.x:9200
Loading packet capture file(s)
../test_pcaps/test_http.pcap
[ERROR]  global name 'count' is not defined

Just for your reference, the Elasticsearch cluster I'm using is version 2.1.

Thanks!

Federico

**Comment by vichargrave** [comment]
I think this one is fixed.  Give it a try and let me know.

**Comment by srpatatas** [comment]
It works now! Thank you!!

**Comment by srpatatas** [comment]
Hi Vic, sorry, I found another error now:

/usr/local/src/espcap/src/espcap.py
--file=/usr/local/src/espcap/test_pcaps/test_dns.pcap --node=
172.30.24.21:9200

Loading packet capture file(s)
/usr/local/src/espcap/test_pcaps/test_dns.pcap
[ERROR]  'NoneType' object has no attribute 'readlines'

**Comment by vichargrave** [comment]
I don't get that error.  I use Anaconda Python which is the latest Python 2.7.10.  Here is the version of Python I'm using and the install modules:

Python 2.7.11 |Anaconda 2.3.0 (x86_64)| (default, Dec  6 2015, 18:57:58)
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org

ablog (0.8.1)
abstract-rendering (0.5.1)
alabaster (0.7.6)
appnope (0.1.0)
appscript (1.0.1)
argcomplete (0.8.9)
astropy (1.0.4)
Babel (2.1.1)
backports.ssl-match-hostname (3.4.0.2)
bcolz (0.9.0)
beautifulsoup4 (4.3.2)
binstar (0.11.0)
bitarray (0.8.1)
blaze (0.8.0)
blz (0.6.2)
bokeh (0.9.0)
boto (2.38.0)
Bottleneck (1.0.0)
cdecimal (2.3)
certifi (14.5.14)
cffi (1.1.0)
click (5.1)
clyent (0.3.4)
colorama (0.3.3)
conda (3.18.9)
conda-build (1.14.1)
conda-env (2.4.5)
configobj (5.0.6)
cryptography (0.9.1)
Cython (0.22.1)
cytoolz (0.7.3)
datashape (0.4.5)
decorator (4.0.4)
docutils (0.12)
elasticsearch (2.1.0)
enum34 (1.0.4)
fastcache (1.0.2)
Flask (0.10.1)
funcsigs (0.4)
futures (3.0.3)
gevent (1.0.1)
gevent-websocket (0.9.3)
glueviz (0.5.3)
greenlet (0.4.7)
grin (1.2.1)
h5py (2.5.0)
idna (2.0)
impacket (0.9.13)
invoke (0.11.1)
ipaddress (1.0.7)
ipykernel (4.1.1)
ipython (4.0.0)
ipython-genutils (0.1.0)
itsdangerous (0.24)
jdcal (1.0)
jedi (0.9.0)
Jinja2 (2.8)
jsonschema (2.4.0)
jupyter-client (4.1.1)
jupyter-core (4.0.6)
llvmlite (0.5.0)
Logbook (0.12.3)
lxml (3.4.4)
MarkupSafe (0.23)
matplotlib (1.4.3)
mistune (0.7.1)
mock (1.0.1)
multipledispatch (0.4.7)
nbconvert (4.0.0)
nbformat (4.0.1)
networkx (1.10)
nltk (3.1)
nose (1.3.7)
notebook (4.0.6)
numba (0.19.1)
numexpr (2.4.3)
numpy (1.9.3)
odo (0.3.2)
openpyxl (1.8.5)
pandas (0.16.2)
path.py (0.0.0)
patsy (0.3.0)
pcapy (0.10.9)
pep8 (1.6.2)
pexpect (3.3)
pickleshare (0.5)
Pillow (3.0.0)
pip (7.1.2)
ply (3.6)
psutil (3.2.2)
ptyprocess (0.5)
py (1.4.27)
pyasn1 (0.1.7)
PyAudio (0.2.7)
pycosat (0.6.1)
pycparser (2.14)
pycrypto (2.6.1)
pycurl (7.19.5.1)
pydot (1.0.2)
pyflakes (1.0.0)
Pygments (2.0.2)
pyOpenSSL (0.15.1)
pyparsing (2.0.3)
pyshark (0.3.5)
pytest (2.7.1)
python-dateutil (2.4.2)
pytz (2015.6)
PyYAML (3.11)
pyzmq (14.7.0)
qtconsole (4.1.0)
redis (2.10.5)
requests (2.9.0)
rope (0.9.4)
rq (0.5.6)
runipy (0.1.3)
scikit-image (0.11.3)
scikit-learn (0.16.1)
scipy (0.16.0)
setuptools (18.8.1)
simplegeneric (0.8.1)
six (1.10.0)
snowballstemmer (1.2.0)
sockjs-tornado (1.0.1)
Sphinx (1.3.1)
sphinx-bootstrap-theme (0.4.8)
sphinx-rtd-theme (0.1.7)
spyder (2.3.7)
SQLAlchemy (1.0.5)
statsmodels (0.6.1)
sympy (0.7.6)
tables (3.2.0)
terminado (0.5)
textblob (0.11.0)
toolz (0.7.2)
tornado (4.2.1)
traitlets (4.0.0)
trollius (1.0.4)
ujson (1.33)
unicodecsv (0.9.4)
urllib3 (1.12)
Werkzeug (0.10.4)
wheel (0.26.0)
xlrd (0.9.3)
XlsxWriter (0.7.3)
xlwings (0.3.5)
xlwt (1.0.0)

I don't see readlines in this list, so I'm not sure why you are getting that error.  When you get a chance would you check your Python version and module list.  You don't need all those modules, but some of them.  Also make sure you installed the version of Pyshark and trollies I specified in the README.  I'm sure you did that, but I just want to double check.  

Thanks.

**Comment by srpatatas** [comment]
Just updated my previous comment but I'll reply anyway with it for clarity:

I'm using Debian 8.2 and Python 2.7.9, here are the installed modules
Django==1.7.7
Logbook==0.12.3
PAM==0.4.2
Pillow==2.6.1
Pygments==2.0.1
SOAPpy==0.12.22
Twisted-Core==14.0.2
argparse==1.2.1
carbon==0.9.12
cffi==0.8.6
characteristic==0.1.0
chardet==2.3.0
click==6.2
colorama==0.3.2
cryptography==0.6.1
defusedxml==0.4.1
django-tagging==0.3.1
docutils==0.12
easysnmp==0.2.4
elasticsearch==2.1.0
futures==3.0.3
graphite-web==0.9.12
html5lib==0.999
lxml==3.5.0
ndg-httpsclient==0.3.2
ply==3.4
psycopg2==2.5.4
py==1.4.31
pyOpenSSL==0.14
pyasn1==0.1.7
pyasn1-modules==0.0.5
pycparser==2.10
pyparsing==2.0.3
pyserial==2.6
pyshark==0.3.5
python-apt==0.9.3.12
python-debian==0.1.27
python-debianbts==1.11
pytz==2012c
reportbug==6.6.3
requests==2.4.3
roman==2.0.0
service-identity==1.0.0
simplejson==3.6.5
six==1.8.0
sqlparse==0.1.13
trollius==1.0.4
urllib3==1.9.1
wheel==0.24.0
whisper==0.9.12
wsgiref==0.1.2
wstools==0.4.3
zope.interface==4.1.1

I'll give it a try with anaconda...

**Comment by vichargrave** [comment]
I suppose you could try installing readlines.  Before going the Anaconda route, do that if you don’t mind.

thanks.

— vic

**Comment by vichargrave** [comment]
I just tried escape on CentOS with the DNS test cap file and it worked.  Just an FYI.  We'll figure out your problem one way or another.

**Comment by srpatatas** [comment]
I don't think readlines is a module, I tried with "pip install readlines" and I didn't find anything...

**Comment by vichargrave** [comment]
I’m thinking it may be a Python version issue.  Can you upgrade your Python version to 2.7.10 then retest?  If that fixes it then I’ll update the README to indicate this version of Python is a requirement.  While I’m at it I should probably test with Python 3.x.

**Comment by srpatatas** [comment]
And looking at the code it seems that the error points to the fp.readlines() method, but I tried these lines on the python interpreter and they work just fine:

root@KAMAILIO:/usr/local/src/espcap/src# /usr/bin/python2.7
Python 2.7.9 (default, Mar  1 2015, 12:57:24) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> test = os.path.isfile('../conf/protocols.list')
>>> print test
True
>>> fp = open('../conf/protocols.list')
>>> protocols = fp.readlines()
>>> supported_protocols = {}
>>> for protocol in protocols:
...     protocol = protocol.strip()
...     supported_protocols[protocol] = 1
... 
>>> print supported_protocols
{'fcgi': 1, 'jxta': 1, 'cba_pdev': 1, 'crtp': 1, 'waveagent': 1, 'netanalyzer': 1, 'vrrp': 1, 'vxlan': 1, 'gdsdb': 1, 'turbocell_aggregate': 1, 'docsis_dsareq': 1, 'sgsap': 1, 'mpeg-pes': 1, 'cmd': 1, 'mp4': 1, 'zbee_zcl_general.identify': 1, 'gsm_a.ccch': 1, 'vxi11_core': 1, 'cms': 1, 'cpfi': 1, 'gluster.dump': 1, 'cmp': 1, 'njack': 1, 'infiniband_sdp': 1, 'ehdlc': 1, 'docsis_regreq': 1, 'aim': 1, 'mpeg': 1, 'idmp': 1, 'bittorrent': 1, 'pn_mrp': 1, 'aruba_iap': 1, 'isis.psnp': 1, 'ftserver': 1, 'dec_stp': 1, 'sscop': 1, 'xtp': 1, 'itunes': 1, 'x2ap': 1, 'diameter': 1, 'pathport': 1, 'vp8': 1, 'brp': 1, '9p': 1, 'wmx.aas_beam': 1, 'giop-coseventcomm': 1, 'gsm_a.bssmap': 1, 'atn-cpdlc': 1, 'dns': 1, 'lwm': 1, 'lbtrm': 1, 'hp_erm': 1, 'lbtru': 1, 'turnchannel': 1, 'ltp': 1, 'ypserv': 1, 'sipfrag': 1, 'tns': 1, 'lisp-data': 1, 'erf': 1, 'mq': 1, 'mp': 1, 'glusterd.friend': 1, 'cba_grouperror': 1, 'kpasswd': 1, 'smtp': 1, [....]

Unless it's something else...

**Comment by vichargrave** [comment]
I think we have a minimum version of Python requirement.  Perhaps you should bite the bullet and install Anaconda.  Just a thought.

**Comment by srpatatas** [comment]
I guess you're right, it must be something with the Python version. I downloaded and installed Anaconda with the modules you required and now it works flawlessly...

Thanks for your help!!

**Comment by vichargrave** [comment]
OK great.  I'm going to close this issue.

**Comment by frameloss** [comment]
I can reproduce this on debian sid, python 2.7.11, executing relative to the install directory fixes the issue:

```
$ pwd
/home/espcap
$ /opt/espcap/src/espcap.py --nic=lo
[ERROR]  'NoneType' object has no attribute 'readlines'
$ cd /opt/espcap/
$ /opt/espcap/src/espcap.py --nic=lo
Packet no. 1
* protocol        - tcp
* file date UTC   - 2016-06-11T07:38:37+0000
* sniff date UTC  - 2016-06-11T07:38:40+0000
* sniff timestamp - 1465630720.91
* layers
	ip {'checksum_bad': '0', 'checksum_good': '0', 'ttl': '64', 'id': '0x00006793', 'dsfield': '0x00000000', 'addr': '127.0.0.1', 'proto': '6', 'flags_rb': '0', 'dst': '127.0.0.1', 'version': '4', 'flags_mf': '0', 'dsfield_dscp': '0', 'hdr_len': '5', 'len': '60', 'dsfield_ecn': '0', 'host': '127.0.0.1', 'frag_offset': '0', 'src': '127.0.0.1', 'checksum': '0x0000d526', 'flags_df': '1', 'dst_host': '127.0.0.1', 'flags': '0x00000002', 'src_host': '127.0.0.1'}
```

**Comment by vichargrave** [comment]
I’ll have to figure out what is going on with Debian.  You can file an issue if you want.
