### ISSUE TITLE
problem with es and dots

### ISSUE THREAD

**Issue by danielguerra69** [vichargrave/espcap#7]
In every dump I read, I get ..
Field name [_ws.malformed] cannot contain '.'
Is there a way to fix this ?

**Comment by vichargrave** [comment]
Sorry for the very late reply.  That’s one of the protocols that should be commented out in the conf/protocols.list.  Make sure that is so you don’t have to deal with it.  On the other hand, if you want it (honestly I’m not sure what it us for) then you’ll have to change the string “_ws.malformed” to something like “_ws_malformed” before it is stored in Elasticsearch.

**Comment by danielguerra69** [comment]
Hi,

I have it commented, from your git. I also tried to build it on top of the
wireshark git. The latest tshark has an option to output to elastic (-T
ek). It just needs a tool to post it to elastic.
Thanks for looking at it.

Regards,

Daniel

Op 28 jul. 2016 9:47 PM schreef "Vic Hargrave" <notifications@github.com>:

**Comment by vichargrave** [comment]
Ok.   Supposedly tshark has a json output, but it doesn’t seem to work.  I build the latest code but no luck so far.

**Comment by danielguerra69** [comment]
es5 should accept dots again, and es2+ could be configured to accept dots ....
My question, on what os,wireshark and es version is the project based ?
