### ISSUE TITLE
Receiving errors by trying to index new pcap file

### ISSUE THREAD

**Issue by masterjohn2016** [vichargrave/espcap#8]
Hi,
I receive errors when I am trying to index a new pcap file:

> ERROR  (u'1 document(s) failed to index.', [{u'create': {u'status': 400, u'_type': u'pcap_file', u'_id': u'AVeAZVHdcN472_kiUUVy', u'error': {u'reason': u"Field name [_ws.malformed] cannot contain '.'", u'type': u'mapper_parsing_exception'}, u'_index': u'packets-2016-09-28'}}])

My setup is running on Elasticsearch 2.4. To index the example pcaps from folder "test_pcaps" is working fine!

Thanks & Regards,
John

**Comment by vichargrave** [comment]
Let me give it a try with ES 2.4.

-- Vic

**Comment by vichargrave** [comment]
I just double checked with Elasticsearch 2.4.0.  Are you sure your input file is valid pcap format?  Perhaps you can send it to me and I can try it out.

**Comment by masterjohn2016** [comment]
Hi Vic,

I double checked my setup with your requirements. I am using pyshark 0.3.6
and not 0.3.5 but I do not think, that this is the problem. The pcap which
I am trying to import was created with tshark (not tcpdump), so the pcap
should be a valid format. Maybe there are some not valid packets in that
pcap?

Attached you will find my test capture as zip archive.

Many thanks for your help!

Regards,
John

2016-10-02 5:12 GMT+02:00 Vic Hargrave <notifications@github.com>:

**Comment by vichargrave** [comment]
There doesn’t seem to be a file attached.  Did you forget to send it or has my email client gone bonkers?

**Comment by masterjohn2016** [comment]
Could you send me your mail address?

Am Sonntag, 2. Oktober 2016 schrieb Vic Hargrave :

> There doesn’t seem to be a file attached. Did you forget to send it or has
> my email client gone bonkers?
>
> > On Oct 2, 2016, at 6:43 AM, masterjohn2016 <notifications@github.com

**Comment by vichargrave** [comment]
Yeah sure.  It is vichargrave@gmail.com.

**Comment by vichargrave** [comment]
I have fixed this issue.  The _ws.expert layer name has been changed to [Malformed_Packet].  There are other _ws.* layers that have to be converted to more functional names, but I'll get to that later.
